import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-700 antialiased">
        <div className="mx-auto h-auto w-full max-w-[33.75rem] bg-white">{children}</div>
      </body>
    </html>
  )
}
